/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.loginController;
import Modelo.usuarioDAO;
import java.awt.Color;

/**
 *
 * @author Sebastian
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxtLoginUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtnIniciar = new javax.swing.JButton();
        jbtnSalirLogin = new javax.swing.JButton();
        jtxtLoginContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlabelErrorUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(167, 215, 219));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel3.setText("Usuario:");

        jtxtLoginUsuario.setBackground(new java.awt.Color(167, 215, 219));
        jtxtLoginUsuario.setForeground(new java.awt.Color(102, 102, 102));
        jtxtLoginUsuario.setText("Ingrese su usuario");
        jtxtLoginUsuario.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jtxtLoginUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtLoginUsuarioMousePressed(evt);
            }
        });
        jtxtLoginUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtLoginUsuarioKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel4.setText("Password:");

        jbtnIniciar.setBackground(new java.awt.Color(0, 102, 255));
        jbtnIniciar.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jbtnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnIniciar.setText("Iniciar Sesion");
        jbtnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jbtnSalirLogin.setBackground(new java.awt.Color(0, 102, 255));
        jbtnSalirLogin.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jbtnSalirLogin.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSalirLogin.setText("Salir");
        jbtnSalirLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jtxtLoginContraseña.setBackground(new java.awt.Color(167, 215, 219));
        jtxtLoginContraseña.setForeground(new java.awt.Color(51, 51, 51));
        jtxtLoginContraseña.setText("********");
        jtxtLoginContraseña.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jtxtLoginContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtLoginContraseñaMousePressed(evt);
            }
        });
        jtxtLoginContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtLoginContraseñaKeyPressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen3.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login1.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login2.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login3.png"))); // NOI18N

        jlabelErrorUsuario.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jlabelErrorUsuario.setForeground(new java.awt.Color(204, 0, 0));
        jlabelErrorUsuario.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabelErrorUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jtxtLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtnSalirLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtnIniciar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtLoginContraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(54, 54, 54)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(9, 9, 9)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtLoginContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addComponent(jlabelErrorUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnIniciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSalirLogin)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 230, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, 390));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imagen3.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, -10, 320, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtLoginUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtLoginUsuarioKeyPressed
        // TODO add your handling code here:
        if (jtxtLoginUsuario.getText().equals("Ingrese su usuario")) {
            jtxtLoginUsuario.setText("");
            jtxtLoginUsuario.setForeground(Color.black);
        }
        if (String.valueOf(jtxtLoginContraseña.getPassword()).isEmpty()) {
            jtxtLoginContraseña.setText("********");
            jtxtLoginContraseña.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_jtxtLoginUsuarioKeyPressed

    private void jtxtLoginContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtLoginContraseñaKeyPressed
        // TODO add your handling code here:
        if (String.valueOf(jtxtLoginContraseña.getPassword()).equals("********")) {
            jtxtLoginContraseña.setText("");
            jtxtLoginContraseña.setForeground(Color.black);
        }
        if (jtxtLoginUsuario.getText().isEmpty()) {
            jtxtLoginUsuario.setText("Ingrese su usuario");
            jtxtLoginUsuario.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jtxtLoginContraseñaKeyPressed

    private void jtxtLoginUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLoginUsuarioMousePressed
        // TODO add your handling code here:
        if (jtxtLoginUsuario.getText().equals("Ingrese su usuario")) {
            jtxtLoginUsuario.setText("");
            jtxtLoginUsuario.setForeground(Color.black);
        }
        if (String.valueOf(jtxtLoginContraseña.getPassword()).isEmpty()) {
            jtxtLoginContraseña.setText("********");
            jtxtLoginContraseña.setForeground(new Color(51,51,51));
        }
    }//GEN-LAST:event_jtxtLoginUsuarioMousePressed

    private void jtxtLoginContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLoginContraseñaMousePressed
        // TODO add your handling code here:
        if (String.valueOf(jtxtLoginContraseña.getPassword()).equals("********")) {
            jtxtLoginContraseña.setText("");
            jtxtLoginContraseña.setForeground(Color.black);
        }
        if (jtxtLoginUsuario.getText().isEmpty()) {
            jtxtLoginUsuario.setText("Ingrese su usuario");
            jtxtLoginUsuario.setForeground(new Color(102,102,102));
        }
    }//GEN-LAST:event_jtxtLoginContraseñaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        usuarioDAO loDAO = new usuarioDAO();
        Login lo = new Login();
        Software l = new Software();
        loginController loC = new loginController(lo, loDAO, l);
        lo.setVisible(true);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnIniciar;
    public javax.swing.JButton jbtnSalirLogin;
    public javax.swing.JLabel jlabelErrorUsuario;
    public javax.swing.JPasswordField jtxtLoginContraseña;
    public javax.swing.JTextField jtxtLoginUsuario;
    // End of variables declaration//GEN-END:variables
}
